#该文件中配置红包服务的测试环境配置数据
red:
  remark: '{cipher}AQBuPHrCORDVK2xzymsCfmbhEUoeajAmGVFfArAi4DYF5dGqRMyIx+wmTB+bVl+AomKjdAYeAd724VCFFo5L8DJRHCCSGkT7V5RTRUHLntiDNX4tpGpIPONyXF3qRHMxUk2jstGUWePdYrOA85UfU/UmWYkFWRPC8L5xAzgy+75w3YYr8dCseiyCCt/uDWokgog6tTw0cPGLEm+m1PzlKvTo4/PKBHgvPzSedtedF5N1Nua+srQWgMLUqcqEXk27mCCQmYC/2pNKl5M7YyBBmi+s1oH/8ltSAmwR0duwfeOAI8O/G1Edojgc+pIkipoeuPc4zSBsHCs6QvOwsqgX0+EDangB7ONgyD7FZhkKgwrj1nHWAbBmMLfuLkxn3U8B6BE='
